default: styles/application.scss
mastodon-bird-ui-auto: styles/mastodon-bird-ui-auto.scss
mastodon-bird-ui-accessible: styles/mastodon-bird-ui-accessible.scss
mastodon-bird-ui-accessible-plus: styles/mastodon-bird-ui-accessible-plus.scss
