shared:
  deepl:
    api_key: <%= ENV.fetch('DEEPL_API_KEY', nil)&.to_json %>
    plan: <%= ENV.fetch('DEEPL_PLAN', 'free') %>
  libre_translate:
    api_key: <%= ENV.fetch('LIBRE_TRANSLATE_API_KEY', nil)&.to_json %>
    endpoint: <%= ENV.fetch('LIBRE_TRANSLATE_ENDPOINT', nil)&.to_json %>
  lingvanex:
    endpoint: <%= ENV.fetch('LINGVANEX_TRANSLATE_ENDPOINT', nil)&.to_json %>
